### PR TITLE
Handle any casing for `ipHeader` option

### PR DESCRIPTION
**Pull request by scottgonzalez**
Fixes gh-19

### CODE REVIEW

**Comment by kpollich** [comment]
Looks good to me.

**Comment by jflewis** [comment]
Did you want his to fail as per the issue gh-19

**Comment by scottgonzalez** [comment]
@jflewis What do you mean?

**Comment by jflewis** [comment]
`...so if the header provided has mixed casing it will fail` @scottgonzalez

**Comment by scottgonzalez** [comment]
That's what this is fixing. It forces the provided value to be lowercase.

**Comment by jflewis** [comment]
ah, yes. I'm reading the issue wrong :( . Looks goods 👍

**Pull request closed without merging**
